solve point failure change bank now included some code changes

diff --git a/effect_maker b/effect_maker
--- a/effect_maker
+++ b/effect_maker
@@ -3,10 +3,25 @@
 ### Values ##################################################
 
 user_values=("0" "0" "0" "0" "0" "0" "0" "0" "0" "0" )
-bank_effect=("leer" "leer" "leer" "leer" "leer" "leer" "leer" "leer" "leer" "leer")
+bank_effect=("leer" "leer" "leer" "leer" "leer" "leer" "leer" "leer" "leer" "leer" "leer" "leer")
 option_key=("a" "y" "s" "x" "d" "c" "f" "v" "g" "b" "h" "n" "j" "m" "k" "," "l" "." "ö" "-")
-control_key=("r" "u" "o" "1-9" "p")
-control_key_desc=("Reset Values" "Load Values" "Save Values" "Load Bank" "Play Testsound")
+control_key=("r" "u" "o" "1-9" "p" "0")
+control_key_desc=("Reset Values" "Load Values" "Save Values" "Load Bank" "Play Testsound" "Switch Bank")
+
+### function delete_bank ########################################
+function delete_bank {
+	printf " Which bank do you want to remove? :"
+	read which_bank
+	delete_bank_name="${bank_effect[$which_bank-1]}"
+	rm "savenload/$delete_bank_name"
+	bank_effect[$which_bank-1]="leer"
+	if [[ "$EFFECT_NAME" -eq "$delete_bank_name" ]]; then
+		unset effect_options
+       		unset max_values
+        	unset step_size
+        	unset user_values
+	fi
+}
 
 ### function reset ##############################################
 function reset_user_values {
@@ -24,7 +39,6 @@ unset index
 function load_user_values {
 if [[ -e savenload/$EFFECT_NAME ]]; then 
 	load_values=( $( cat savenload/$EFFECT_NAME ) )
-	error1=${#load_values[*]}
 	i=1
 	index="${#load_values[*]}"
 	while [[ "$i" -lt "$index" ]]; do
@@ -38,20 +52,17 @@ unset index
 
 ### funktion save  ##############################################
 function save {
-echo "save now"
-temp_effect="$EFFECT_NAME"
-i=0
-index="${#effect_options[*]}"
-while [[ "$i" -lt "$index" ]]; do
-        if [[ $( echo "${user_values[$i]} < 1 " |bc ) -eq "1" && $( echo "${user_values[$i]} > 0 " |bc ) -eq "1" ]]; then
-                usr_values='0'"${user_values[$i]}"
-        else
-                usr_values="${user_values[$i]}"
-        fi
-        temp_effect="$temp_effect"' '"$usr_values"
-        i=$[$i+1]
-done
-echo $temp_effect > "savenload/$EFFECT_NAME"
+if ! [[ -z "$EFFECT_NAME" ]]; then
+	temp_effect="$EFFECT_NAME"
+	i=0
+	index="${#effect_options[*]}"
+	while [[ "$i" -lt "$index" ]]; do
+	        usr_values="${user_values[$i]}"
+		temp_effect="$temp_effect"' '"$usr_values"
+	        i=$[$i+1]
+	done
+	echo $temp_effect > "savenload/$EFFECT_NAME"
+fi
 unset i
 unset index
 unset usr_values
@@ -60,15 +71,33 @@ unset usr_values
 
 ### Function preload ########################################
 function preload {
-
+save
 EFFECTS_FOLDER='effect_desc/'
 ls $EFFECTS_FOLDER > /var/tmp/effect_maker
-cat -n /var/tmp/effect_maker
-printf '\nChoose an effect in integer :'
-read CHOOSE_EFFECT
-EFFECT_NAME=$(tail +$CHOOSE_EFFECT /var/tmp/effect_maker | head -1)
-
-bank_effect[$1-1]=$EFFECT_NAME
+printf "\n"
+if ! [[ "$1" -eq "0" ]]; then
+	cat -n /var/tmp/effect_maker
+	printf '\nChoose an effect in integer :'
+	read CHOOSE_EFFECT
+	EFFECT_NAME=$(tail +$CHOOSE_EFFECT /var/tmp/effect_maker | head -1)
+	bank_effect[$1-1]=$EFFECT_NAME
+else
+	x=0
+	z="${#bank_effect[*]}"
+	while [[ "$x" -lt "$z" ]]; do 
+		t=$[$x+1]
+		if ! [[ "${bank_effect[$x]}" == "leer" ]]; then
+			printf "$t"'. '"${bank_effect[$x]}  "
+		fi
+		x=$[$x+1]
+		if [[ $( echo "$t % 6 |bc" ) -eq "0" ]]; then
+			printf "\n"
+		fi
+	done
+	printf "Which bank do you want to switch to: "
+	read CHOOSE_EFFECT
+	EFFECT_NAME="${bank_effect[$CHOOSE_EFFECT-1]}"
+fi
 EFFECT=( $( cat $EFFECTS_FOLDER""$EFFECT_NAME ) )
 
 index="${#EFFECT[*]}"
@@ -82,9 +111,13 @@ while [[ "$i" -lt "$index" ]]; do
 	i=$[$i+4]
 	y=$[$y+1]
 done
-
+if  [[ "$1" -eq "0" ]]; then
+	load_user_values
+fi
 unset i
 unset y
+unset x
+unset z
 unset index
 unset CHOOSE_EFFECT
 }
@@ -115,7 +148,7 @@ unset max
 ### Function gui_bank ########################################
 function gui_bank {
 i=0
-index=10
+index="${#bank_effect[*]}"
 while [[ "$i" -lt "$index" ]]; do
 	y=$[$i+1]
 	if [[ "$y" -gt 9 ]]; then
@@ -267,41 +300,35 @@ case "$1" in
 	p) sox_play ;;
 	u) load_user_values ;;
 	r) reset_user_values ;;
-	[1-9]) preload $1 ;;
+	o) save ;;
+	z) delete_bank ;;
+	[0-9]) preload $1 ;;
+	*)
+		i=0
+		y=0
+		index=${#option_key[*]}
+		while [[ "$i" -lt "$index" ]]; do
+			if [[ "$1" = "${option_key[$i]}" ]]; then
+				if [[ $( echo "$i % 2" | bc ) -eq "0" ]]; then
+				        if [[ $( echo "${user_values[$y]} < ${max_values[$y]}" |bc ) -eq "1" ]]; then 	user_values[$y]=$( echo "${user_values[$y]}+${step_size[$y]}" | bc ); fi
+				else
+				        if [[ $( echo "${user_values[$y]} > 0" |bc ) -eq "1" ]]; then user_values[$y]=$( echo "${user_values[$y]}-${step_size[$y]}" | bc ); fi
+				fi
+				### repair point failure
+		                usr_val_str=${user_values[$y]}
+				if [[  ${usr_val_str:0:1} == "." ]]; then
+	        	                user_values[$y]='0'"${user_values[$y]}"
+		                fi
+				i=$index
+			fi
+			i=$[$i+1]
+			if [[ $( echo "$i % 2" | bc ) -eq "0" ]]; then y=$[$y+1]; fi
+		done
+		unset usr_val_str
+		unset i
+		unset y
+		unset index ;;
 esac
-#  if [[ "$1" = "q" ]]; then stop=1
-#elif [[ "$1" = "p" ]]; then sox_play
-#elif [[ "$1" = "u" ]]; then load_user_values
-#elif [[ "$1" = 1 ]]; then preload 1
-#elif [[ "$1" = 2 ]]; then preload 2
-#elif [[ "$1" = 3 ]]; then preload 3
-#elif [[ "$1" = 4 ]]; then preload 4
-#elif [[ "$1" = 5 ]]; then preload 5
-#elif [[ "$1" = 6 ]]; then preload 6
-#elif [[ "$1" = 7 ]]; then preload 7
-#elif [[ "$1" = 8 ]]; then preload 8
-#elif [[ "$1" = 9 ]]; then preload 9
-#elif [[ "$1" = 10 ]]; then preload 10
-#fi
-
-i=0
-y=0
-index=${#option_key[*]}
-while [[ "$i" -lt "$index" ]]; do
-	if [[ "$1" = "${option_key[$i]}" ]]; then
-		if [[ $( echo "$i % 2" | bc ) -eq "0" ]]; then
-		        if [[ $( echo "${user_values[$y]} < ${max_values[$y]}" |bc ) -eq "1" ]]; then user_values[$y]=$( echo "${user_values[$y]}+${step_size[$y]}" | bc ); fi
-		else
-		        if [[ $( echo "${user_values[$y]} > 0" |bc ) -eq "1" ]]; then user_values[$y]=$( echo "${user_values[$y]}-${step_size[$y]}" | bc ); fi
-		fi
-		i=$index
-	fi
-	i=$[$i+1]
-	if [[ $( echo "$i % 2" | bc ) -eq "0" ]]; then y=$[$y+1]; fi
-done
-unset i
-unset y
-unset index
 }
 ### Working zone ##########################################
 clear
